name: Publish Nuget

on: 
  push:
    branches: 
      - master

jobs:
  publish:
    name: Publish to Nuget
    runs-on: windows-latest
    
    
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Optional step, add only for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl for a list of software that comes pre-installed with ubuntu-latest / windows-latest
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 3.0.101

      - name: Build
        run: dotnet build
        working-directory: src/Unicorn.Utilities
        
      # Publish
      - name: Publish if version is updated
        uses: rohith/publish-nuget@v1
        with: # All inputs are optional (details given below)
           project_dir: src/Unicorn.Utilities # Defaults to repository root
           tag_format: v* # [*] gets replaced with version
           nuget_key: ${{ secrets.NUGET_API_KEY }} # nuget.org API key
